// {
//     id: 1,
//     name: 'allenamento',
//     low: '3 flessioni',
//     medium: '5 flessioni',
//     high: '15 flessioni',
//   },
//   {
//     id: 2,
//     name: 'bere acqua',
//     low: '3 bicchieri',
//     medium: '5 bicchieri',
//     high: '15 bicchieri',
//   },
//   {
//     id: 3,
//     name: 'Studiare ML1',
//     low: '20 minuti',
//     medium: '50 minuti',
//     high: '90 minuti',
//   },
//   {
//     id: 4,
//     name: 'Studiare ML2',
//     low: '20 minuti',
//     medium: '50 minuti',
//     high: '90 minuti',
//   },
//   {
//     id: 5,
//     name: 'Studiare ML3',
//     low: '20 minuti',
//     medium: '50 minuti',
//     high: '90 minuti',
//   },
//   {
//     id: 6,
//     name: 'Studiare ML4',
//     low: '20 minuti',
//     medium: '50 minuti',
//     high: '90 minuti',
//   },